### ISSUE TITLE
One way relationship between the "I'm the clue reader checkbox" and the role indicator.

### ISSUE THREAD

**Issue by bgreenawald** [bgreenawald/madgab-online#27]
It appears that the relationship between the "I'm the clue reader checkbox" and the "Role" indicator is one way.

![image](https://user-images.githubusercontent.com/8428972/95693409-35f65e00-0bfa-11eb-8fd3-2a2a40df720d.png)

Clicking the checkbox affects the toggle but flipping the toggle does not affect the checkbox. Also, the checkbox will flip the toggle regardless of its current value, leading to inconsistent behavior.

**Comment by JocelynYH** [comment]
Hmmm, the layout also looks strange - what browser are you on? Are you on chrome?

**Comment by bgreenawald** [comment]
I am on Chrome but that also isn't the full layout, just the relevant portion of it.

**Comment by JocelynYH** [comment]
Was the alignment all weird like that though?

**Comment by bgreenawald** [comment]
It looks normal to me but I'm not sure what it's suppose to look like.

**Comment by JocelynYH** [comment]
Oooh, you just took a snippet of the page - this isn't the full screen right? 

This is what the page looks like on my screen: 
![Uploading Screen Shot 2020-10-12 at 6.04.09 PM.png…]()

**Comment by bgreenawald** [comment]
Yeah I just took an off-center snippet

**Comment by JocelynYH** [comment]
Just pushed up a fix!
