### ISSUE TITLE
Some clues potentially inappropriate

### ISSUE THREAD

**Issue by bgreenawald** [bgreenawald/madgab-online#31]

**Comment by bgreenawald** [comment]
@JocelynYH What sort of criteria should we be using the determine if a clue is appropriate?

**Comment by JocelynYH** [comment]
It was remarked that the particular inappropriate clue noticed was some sort of sexual innuendo.

**Comment by bgreenawald** [comment]
I ran all of the clues through Azure's Content Moderation API and will upload the results shortly. Do you think we should try and add a user option to include potentially offensive clues or just go ahead and remove them for now?

**Comment by bgreenawald** [comment]
Attached are two files, the list of clues that the API flagged as potentially sensitive, and the list of clues that for whatever reason it chose not to categorize.

From the lists, I'm removing the following clues:
1. As high as a kite
2. Beast with two backs
3. Beavis and ButtHead
4. Birds and the bees
5. Blonde bombshell
6. Bodice ripper
7. Cock and bull story
8. Colder than a witch's tit
9. Cut of your jib
10. Dog's bollocks
11. Full of piss and vinegar
12. Get on my wick
13. Get thee behind me Satan
14. Granny dumping
15. Hard and fast
16. I'll Make Love to You
17. Laid out in lavender
18. Moaning Minnie
19. Nasty brutish and short
20. Piece of piss
21. Piss and vinegar
22. Pull your finger out
23. Sex and shopping
24. Sex and the City
25. Shit for brains
26. Something nasty in the woodshed
27. Son of a bitch
28. Squeaky bum time
29. Sweet Fanny Adams
30. The Joy of Sex
31. The Naked Ape
32. The law is an ass
33. You get on my wick
34. As dead as a doornail

There may be a few I've missed but that should be most of them.

**Comment by bgreenawald** [comment]
Once we're ready to really make this live, we may need to come up with a more robust source of clues. Right now, they just come from various sources I've scraped so the quality and relevance are highly varied.

**Comment by JocelynYH** [comment]
Ack, I did not see your comment from 17 days ago sorry!  - yes definitely for the user feedback option.  I'll build that into the designs.

**Comment by JocelynYH** [comment]
If I ever don't respond to something on github, just text me - I probably just didn't see the email notification github sent me.

**Comment by JocelynYH** [comment]
ngl, some of these flagged phrases are great - for fun, we could have an inappropriate version and a family friend/sfw version
